packageExtensions:
  '@mdx-js/loader@*':
    dependencies:
      'webpack': '*'

  '@mdx-js/react@*':
    dependencies:
      'react': '*'

  '@next/mdx@*':
    dependencies:
      '@mdx-js/react': '*'

  '@testing-library/user-event@*':
    dependencies:
      '@testing-library/dom': '*'

  'babel-loader@*':
    dependencies:
      '@babel/core': '*'
      'webpack': '*'

  'next-pwa@*':
    'dependencies':
      'webpack': '*'

  'type-coverage-core@*':
    dependencies:
      'typescript': '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-stage.cjs
    spec: '@yarnpkg/plugin-stage'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.2.1.cjs
