version: '3.9'

services:
  nextjs:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped

  nginx:
    command: nginx
    depends_on:
      - nextjs
    image: nginx:alpine
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx:ro
